version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    schedule:
      interval: "monthly"
